sudo : required
services:
  - docker

language: node_js

before_install:
  - docker build -t roig/docker-react -f Dockerfile.dev .

script:
  - docker run roig/docker-react npm run test -- --coverage
